[[language]]
name = "typescript"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--stdin-filename", "file.tsx"] }
auto-format = true


[[language]]
scope = "source.kk"
name = "kk"
roots = []
formatter = { command = "/Users/wongjiahau/repos/kk/target/debug/kk", args = ["format"] }
file-types = [{ suffix = ".kk"}]
auto-format = true
grammar = "clojure"

[[language]]
name = "graphql"
language-server = {command = "graphql-lsp", args = ["server", "-m", "stream"], config = {"graphql-config.load.legacy" = true}}

[[language]]
name = "sql"
formatter = { command = "sql-formatter", args = ["-l", "postgresql", "-u"] }
auto-format = true
file-types = [{ suffix = ".sql"}]
