# Refer https://github.com/lighttiger2505/sqls/issues/59#issuecomment-1250090147
# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: psql
    driver: postgresql
    dataSourceName: "host=127.0.0.1 port=5432 user=postgres password='' dbname=postgres sslmode=disable"
